Research: How to fetch the list of articles from Wikidata API #13
wikicurricula-uy/wikicurricula-boilerplate pull request #51
Opened 2023-10-09 19:45 UTC by GonzaFP

Instead of manually copying and pasting article names, I have written a guide on how to fetch and extract articles from Wikidata API

2023-10-16 23:48 UTC, wikicurricula-uy requested changes
I'm sorry, @GonzaFP , do you think you can clean up this PR a bit? I see that 12 files changed in the comparison but that's not correct, right? Which files are you changing in order to achieve this?

2023-10-16 23:48 UTC, wikicurricula-uy commented on data-gathering/__pycache__/bot.cpython-311.pyc
Please remove this

2023-10-16 23:48 UTC, wikicurricula-uy commented on README.md
Can you help me understand which parts of the readme you've changed? Too many lines are highlighted and it's confusing

2023-10-16 23:48 UTC, wikicurricula-uy commented on visualization/assets/script/dv1.js
Do we have any actual changes in dv1.js? Or is it all whitespaces changes and such?

2023-10-16 23:48 UTC, wikicurricula-uy commented on visualization/assets/script/utilities.js
Do we have any actual changes in utilities.js? Or is it all whitespaces changes and such?

2023-10-17 01:02 UTC, GonzaFP commented
@wikicurricula-uy  thanks for the feedback. I only changed the README but let me clean up the PR.

2023-10-17 12:17 UTC, GonzaFP commented on visualization/assets/script/utilities.js
Hello @wikicurricula-uy , It is whitespaces.

2023-10-17 12:34 UTC, GonzaFP commented on README.md
@wikicurricula-uy  this is what I added https://github.com/GonzaFP/wikicurricula-boilerplate/blob/new-branch/README.md#how-to-fetch-the-list-of-articles-from-wikidata-api

2023-10-17 12:37 UTC, GonzaFP commented on data-gathering/__pycache__/bot.cpython-311.pyc
@wikicurricula-uy I have removed it. 
Thanks

2023-10-17 15:07 UTC, wikicurricula-uy commented on README.md
Ok, I think this is already covered by this pull request which was already merged https://github.com/wikicurricula-uy/wikicurricula-boilerplate/pull/57
Let me know if I'm overlooking anything.
I'll close this PR, thanks for your work!

2023-10-17 15:07 UTC, closed without merging